### ISSUE TITLE
CLI Tool + bbx fertigstellen

### ISSUE THREAD

**Issue by carobro** [carobro/Geosoftware2#11]
- [x] Bbox von gesamten Ordner auslesen
- [x] BBX CSV
- [x] BBX ISO
- [x] BBX GeoJson
- [x] BBX GeoTiff
- [x] Datein mit Parametern aufrufen
- [x] Abstraktionseben

- [x] Geopackage Koordinatensystem prüfen
- [x]  GeoJson Koordinatensystem prüfen
- [x] Shapefile Koordinatensystem überprüfen
- [x] Geojson Koordinatensystem überprüfen
- [x] NetCDF Koordinatensystem überprüfen
- [x] CSV Koordinatensystem überprüfen

**Comment by JaFro96** [comment]
Ziemlich simple Möglichkeit: [Fire](https://github.com/google/python-fire)

**Comment by carobro** [comment]
# To DO's:
1. BBX aus CSV, Geopackage
2. BBX aus einem gesammten Ordner

**Comment by corneliazy** [comment]
zum Aufrufen des Tools:
1. in Ordner der .py Datei navigieren
2. "python extractBbox.py --path <Path> "

**Comment by JaFro96** [comment]
NetCDF mit GDAL: https://www.gdal.org/frmt_netcdf.html

**Comment by carobro** [comment]
@corneliazy         
# @see https://www.w3schools.com/python/python_file_remove.asp
        os.remove("out.json")
damit kann die Datei nach ausführen direkt weider gelöscht werden.

**Comment by JaFro96** [comment]
Wie ist das bei Shapefile gedacht. Soll man den Ordner in den Pfad packen, die .shp datei oder noch eine andere? @corneliazy
