### ISSUE TITLE
Neue Seite in Zenodo erstellen

### ISSUE THREAD

**Issue by carobro** [carobro/Geosoftware2#27]

**Comment by JaFro96** [comment]
### Steps to the solution
- [config.py](https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/config.py)
- [Invenio-app](https://github.com/inveniosoftware/invenio-app)
- [ReadTheDocs Zenodo](https://zenodo.readthedocs.io/en/latest/api/deposit.html)

**Comment by nuest** [comment]
@JaFro96 im Chat gab es ja leider keine Reaktion - bist du noch weiter gekommen?

**Comment by JaFro96** [comment]
Nein, bisher leider noch nicht.
