### ISSUE TITLE
Bei welchen Daten sollen die weiteren Vorschläge angezeigt weren ? In Allen oder nur in denen die wir hochladen ?

### ISSUE THREAD

**Issue by carobro** [carobro/Geosoftware2#32]

**Comment by nuest** [comment]
In allen natürlich bei denen die Daten für eine Ähnlichkeitsberechnung vorhanden sind.

Bei Daten ohne raum-zeitliche Metadaten sollte der Algorithmus dann natürlich eine sehr geringe Ähnlichkeit liefern..
