### ISSUE TITLE
CLI Tool + einzelne features extrahieren

### ISSUE THREAD

**Issue by carobro** [carobro/Geosoftware2#35]
- [x] CSV
- [x] ISO
- [x] GeoTiff
- [x] GeoPackage
- [x] NetCDF
- [x] GeoJson
- [x] berechnung des neuen Polygons mit "convex hull" Algorithmus

**Comment by carobro** [comment]
Alles klar

**Comment by JaFro96** [comment]
## Convex Hull
Bei der Beschäftigung mit dem [Convex hull Algorithmus](https://soi.ch/wiki/convex-hull/) ist mir aufgefallen, dass man den gar nicht auf eine Kugel anwenden kann. Ist euch das auch aufgefallen? [Quelle](https://stackoverflow.com/questions/9678624/convex-hull-of-longitude-latitude-points-on-the-surface-of-a-sphere)
