### ISSUE TITLE
API - Connection

### ISSUE THREAD

**Issue by carobro** [carobro/Geosoftware2#39]
- [x]  CLI Tool mit API verbinden
- [ ] Box zum anzeigen von similar Dateien

**Comment by carobro** [comment]
## Für jeden 
- [ ] jeder versucht einmal die Installtion
- [ ]  Test datei über Sandbox hochladen
- [ ] Test Datei auf Zenodo installieren ( um Vorgang zu verstehen)

**Comment by carobro** [comment]
Ein Teil der Gruppe:
Wo müssen wir uns reinhängen

Zweiter Teil:
Endpunkt Datenbankabfrage

**Comment by JaFro96** [comment]
Ich könnte mir vorstellen, dass wir uns hier reihnhängen müssen: 
- zenodo/zenodo/modules/fixtures/files.py

**Comment by carobro** [comment]
Wir wäre es mit  `zenodo/zeodo/modules/deposit/views.py` ?
Oder hier der link zur zenodo dokumentation: https://zenodo.readthedocs.io/en/latest/_modules/zenodo/modules/deposit/views.html#to_links_js
Da gibt es `Rest` und `Post` blueprints

**Comment by carobro** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5bead77a67f0ab000e7d1443/attachments/5c374de4fef389000fe5fc4d)
![image](https://app.gitkraken.com/api/glo/boards/5bead77a67f0ab000e7d1443/attachments/5c374de4fef389000fe5fc4f)

Hier meine Konsolenausgaben

**Comment by nuest** [comment]
Ich finde das sieht _sehr vielversprechend_ aus, also `indexer.py` und auch der Task `invenio_indexer.tasks.index_record`.

Ist die `indexer.py` im Zenodo Quellcode?

Es gibt auch eine Kurzanleitung dazu, wie man Zenodo mit lokalem Invenio-Code laufen lassen kann. Kennst du die?

**Comment by yhallowiegeht** [comment]
@corneliazy closed du das issue heute noch wenns bei dir laeuft? sonst schreib mal pls was noch problematisch ist hier rein. Danke dir :)
