### ISSUE TITLE
CLI-Tool Bugs

### ISSUE THREAD

**Issue by corneliazy** [carobro/Geosoftware2#67]
Hier bitte alle Fehler reinschreiben, die bei der Nutzung des CLI Tools auftauchen :)

**Comment by corneliazy** [comment]
Wenn man mehrere Datensätze nacheinander mit dem CLI Tool verarbeitet, dann werden die returnwerte gespeichert und bei der darauf folgenden Ausgabe wieder mit ausgegeben.
![grafik](https://user-images.githubusercontent.com/38653955/51429774-64582c80-1c12-11e9-81cd-bd64db16b181.png)
![grafik](https://user-images.githubusercontent.com/38653955/51429778-68844a00-1c12-11e9-9b12-9811697f9610.png)
![grafik](https://user-images.githubusercontent.com/38653955/51429780-6f12c180-1c12-11e9-84d4-f4eec9ab0058.png)
Nach einem Neustart von Zenodo geht es wieder von vorne los.

Dieser Fehler taucht auch in den Tests test_mastersim.py auf.

**Comment by corneliazy** [comment]
Der Returnwert der Hauptfunktion sollte eigentlich ein Array sein. (Steht im Code als "return a"). In der Konsolenausgabe von Zenodo wird allerdings kommt allerdings kein Returnwert an.

Code (aus zenodo- datei):
![grafik](https://user-images.githubusercontent.com/38653955/51429893-f90f5a00-1c13-11e9-87a1-fddd43ac16e9.png)

Output in Konsole:
![grafik](https://user-images.githubusercontent.com/38653955/51429902-18a68280-1c14-11e9-9249-7ff03f8f5747.png)

Das seltsame daran ist, dass in der mastersim.py methode des CLI-Tools ein Wert returnt wird, mit dem weitergearbeitet werden kann.

**Comment by carobro** [comment]
Ich weiß nicht wer was geändert hat, aber ich bekomme jetzt trotz unserer click_function im extractTool **wieder** folgenden F
![bildschirmfoto von 2019-01-20 15-16-44](https://user-images.githubusercontent.com/38653703/51440368-aa6ec800-1cc6-11e9-8252-a640194d81ef.png)
ehler

**Comment by carobro** [comment]
Soweit ich beurteilen kann wird unsere Zeit noch nicht nach [ISO8601](https://de.wikipedia.org/wiki/ISO_8601) zurückgegeben

**Comment by JaFro96** [comment]
Wozu ist diese getTimeextent.py Funktion gedacht? Nur zum testen? 
Ich sehe nämlich nicht wie die in unser extractTool.py eingebaut worden ist. Und in jeder DateitypInfo Datei haben wir auch einen Abschnitt, der die Zeit behandelt. 
@carobro @corneliazy

**Comment by corneliazy** [comment]
nein, ich glaube wir brauchen die nicht. Aber 100 prozentig sicher bin ich mir nicht. Deshalb würde ich die jetzt gerade nicht löschen... Du kannst die ja mal umbenennen und gucken, ob das tool noch läuft

**Comment by carobro** [comment]
- [ ] In der time-extraction im extractTool muss der `'str' object is not callable` Fehler für die Tests gehoben werden. Bei der normalen Abfrage läuft alles richtig.   
   
- [ ] weitere Tests für die ConvexHull sind nötig   
   
- [ ] Ordner Extraktion Fehler muss behoben werden

**Comment by carobro** [comment]
- [ ] Test für ConvexHull bei ISO wirft Fehler obwohl sie richtig berechnet wurde. (`test_single.py`)
- [ ] Bei der ConvexenHull für Geopackage  kann ich nicht einschätzen ob das Ergebnis richtig ist. (`test_single.py`)
- [ ] Shapefile-Time wirft schweren Fehler. Habe noch keine Idee woran das liegt. (`test_extractTime.py`)
