### ISSUE TITLE
similar.py minor change

### ISSUE THREAD

**Issue by yhallowiegeht** [carobro/Geosoftware2#72]
**Similarity calculation**
Nicht wirklich ein Bug aber vielleicht eine Misconception. also wenn ich das richtig verstanden habe, dann ergibt die Similarity Calculation bei geringerem sim_value eine hoehere Uebereinstimmung.

also 0.2 hoehere Uebereinstimmung als 0.8. Wobei dann aber 1 die vollstaendige Uebereinstimmung bedeutet. Das ist irgendwo nicht wirklich sinnvoll in meinen Augen, also wenn ihr euch spezifisch was dabei gedacht habt, dann muss ich mir was einfallen lassen, jedenfalls gestaltet sich genau dieser Umstand zur Darstellung im json als problematisch.

Vorschlag waere einfach nur den return-Wert auf 1 - sim zu setzen, dann haette sich das geloest, wollte das nur nochmal abgeklaert haben.

Also in 
>similar.py

```
def calculateScore(bbox1,bbox2):
    if isinstance(bbox1[0], float) and isinstance(bbox1[1], float) and isinstance(bbox1[2], float) and isinstance(bbox1[3], float) and isinstance(bbox2[0], float) and isinstance(bbox2[1], float) and isinstance(bbox2[2], float) and isinstance(bbox2[3], float):
        if  bbox1[0] != bbox2[0] and bbox1[1] != bbox2[1] and bbox1[2] != bbox2[2] and bbox1[3] != bbox2[3]: 
            if distance(bbox1,bbox2) < 20000:
                simdis = distance(bbox1,bbox2)/20000
            else:
                simdis = 1
            if abs(area(bbox1) - area(bbox2)) < 1000000:
                simA = (abs(area(bbox1) - area(bbox2)))/1000000
            else:
                simA = 1
            sim = (2 * simdis + simA)/3
            return 1-sim
        else:
            sim=1
            return sim
    else:
        sim = 1
        return sim
```

**Comment by carobro** [comment]
Also ich versteh noch nicht ganz was das Problem ist, aber wenn dir was aufgefallen ist glaub ich dir dass da etwas nicht sinnvoll war. Das kannst du dann gerne ändern

**Comment by carobro** [comment]
Aber @corneliazy hatte mir auch schon deswegen geschrieben und evtl ist es besser die ganze if else rauszunehmen

**Comment by yhallowiegeht** [comment]
ok hat sich dann, hab es umgeschrieben, wollte aber auch mal ein issue erstellt haben nur zur Sicherheit
